### ISSUE TITLE
PlaybackEngine.js 

### ISSUE THREAD

**Issue by ronnycsharp** [jimutt/osmd-playback-demo#2]
Hi,
may be there is an issue in line 218 in PlaybackEngine.js.
The whole note length should be multiplied, but at the moment the length will be added.

I am working on a player too. But for a mobile application which uses the OSMD-Lib to display notes with CoreMidi. At the moment, I am working on the dynamic expressions with continious and instantaneous expressions. Perhaps we could work together on a player.

Kind regards
Ronny

**Comment by jimutt** [comment]
Hi!
Thank you, yes that definitely looks like a bug. 

Ah, awesome! That could absolutely be interesting. I haven't done any more work on this after I put together this rather rough prototype, but I still very much would like to have a well working player for OSMD. Feel free to share some more information about your project, you could perhaps drop me a message at jimmy@utterstrom.xyz
